# Generated by Django 3.1.7 on 2021-04-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('option1', models.CharField(max_length=180)),
                ('option2', models.CharField(max_length=180)),
                ('option3', models.CharField(max_length=180)),
                ('correctOpt', models.CharField(max_length=180)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QUIZ.quizmodel')),
            ],
        ),
    ]
